# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#   - board: nice_nano_v2
#    shield: settings_reset

---
include:
  # Use central instead of left, when dongle is disabled
  # - board: nice_nano_v2 
  #   artifact-name: infinity_central
  #   shield: corne_central nice_view
  #    snippet: studio-rpc-usb-uart

  # Left + Nice!View
  - board: nice_nano_v2 
    artifact-name: infinity_left
    shield: corne_left nice_view_adapter nice_view
  
  # Right + Nice!View
  - board: nice_nano_v2
    artifact-name: infinity_right
    shield: corne_right nice_view_adapter nice_view

  # Dongle + Nice!View 
  - board: nice_nano_v2 
    artifact-name: infinity_dongle_nice_view
    shield: corne_dongle nice_view_adapter nice_view 
  #    snippet: studio-rpc-usb-uartds

  # Dongle + Prospector
  - board: nice_nano_v2
    shield: corne_dongle prospector_adapter
    artifact-name: infinity_dongle_screen

  # Dongle + Screen
  - board: nice_nano_v2
    shield: corne_dongle dongle_screen
    artifact-name: infinity_dongle_screen

  # Dongle with Logging enabled
  # - board: nice_nano_v2
  #   artifact-name: infinity_dongle_with_logging
  #   shield: corne_dongle nice_view
  #   snippet: zmk-usb-logging
  #    cmake-args: -DCONFIG_ZMK_USB_LOGGING=y
  #    snippet: studio-rpc-usb-uart

  # Central with Logging enabled
  # - board: nice_nano_v2
  #   artifact-name: infinity_central_with_logging
  #   shield: corne_central nice_view
  #   snippet: zmk-usb-logging    
  #    cmake-args: -DCONFIG_ZMK_USB_LOGGING=y
  #    snippet: studio-rpc-usb-uart

  # Reset Settings
  - board: nice_nano_v2
    shield: settings_reset
