# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#   - board: nice_nano_v2
#    shield: settings_reset

---
include:
  - board: nice_nano_v2 
    artifact-name: infinity_central
    shield: corne_central nice_view
#    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2 
    artifact-name: infinity_left
    shield: corne_left nice_view
  - board: nice_nano_v2
    artifact-name: infinity_right
    shield: corne_right nice_view
  - board: nice_nano_v2
    artifact-name: infinity_dongle
    shield: corne_dongle nice_view
#    snippet: studio-rpc-usb-uartds
  - board: nice_nano_v2
    artifact-name: infinity_dongle_with_logging
    shield: corne_dongle nice_view
    cmake-args: -DCONFIG_ZMK_USB_LOGGING=y
#    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    artifact-name: infinity_central_with_logging
    shield: corne_central nice_view
    cmake-args: -DCONFIG_ZMK_USB_LOGGING=y
#    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: settings_reset
