# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#   - board: nice_nano_v2
#    shield: settings_reset

---
include:
  - board: nice_nano_v2 
    shield: corne_left nice_view
    artifact-name: corne_left
  - board: nice_nano_v2 
    shield: corne_central nice_view
    artifact-name: corne_central
  - board: nice_nano_v2
    shield: corne_right nice_view
    artifact-name: corne_right
  - board: nice_nano_v2
    shield: settings_reset
  - board: nice_nano_v2
    shield: corne_dongle nice_view
    artifact-name: corne_dongle
  - board: nice_nano_v2
    shield: corne_dongle nice_view
    cmake-args: -DCONFIG_ZMK_USB_LOGGING=y
    artifact-name: corne_dongle_with_logging
  - board: nice_nano_v2
    shield: corne_central nice_view
    cmake-args: -DCONFIG_ZMK_USB_LOGGING=y
    artifact-name: corne_central_with_logging
