### DONGLE MODE 
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2

### DONGLE OPTIONS 
# 5 profiles (n+2)
CONFIG_BT_MAX_CONN=7
CONFIG_BT_MAX_PAIRED=7

### DISPLAY DONGLE OPTIONS
CONFIG_ZMK_DISPLAY=y
CONFIG_BT_BAS=n
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

### POWER OPTIONS
# Report interval on the battery energy in seconds
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=60
# CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y
# Boost bluetooth power. PLUS_8 can be anything between PLUS_8 and PLUS_20.
# Helps with possible lags and delays
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Combo configuration
CONFIG_ZMK_COMBO_MAX_COMBOS_PER_KEY=8

# Increase polling rate - default is 9ms = 111 hz polling rate, 2ms = 500hz, 1ms = 1000hz
CONFIG_USB_HID_POLL_INTERVAL_MS=1

CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y

CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n

# Enable mouse
CONFIG_ZMK_POINTING=y

# CONFIG_ZMK_STUDIO=y
# CONFIG_ZMK_STUDIO_LOCKING=n

# Prospector Settings
# CONFIG_PROSPECTOR_USE_AMBIENT_LIGHT_SENSOR=y
# CONFIG_LV_Z_VDB_SIZE=25
# CONFIG_PROSPECTOR_STATUS_SCREEN_OPERATOR=y


### DEBUG OPTIONS
# CONFIG_ZMK_USB_LOGGING=y
# CONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=8000

