name: Build ZMK Firmware

on: 
  workflow_dispatch:
  push:
    branches:
      - mdk_working
      - mdk
      - dev
      - dongle_nn
    #    paths:
    #      - "config/*.keymap"
    #      - "config/*.dtsi"
    #      - "config/*.conf"
    #      - "config/west.yml"
    #      - "gauntlet/*.dtsi"
    #      - "gauntlet/*.keymap"
    #      - "**.conf"
    #      - "**.defconf"
    #      - "**.overlay"
  
jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    #uses: urob/zmk/.github/workflows/build-user-config.yml@build-with-submodules
