name: Build ZMK Firmware

on: 
  workflow_dispatch:
  push:
    paths:
      - "config/*.keymap"
      - "config/*.dtsi"
      - "config/*.conf"
      - "config/west.yml"
      - "gauntlet/*.dtsi"
      - "gauntlet/*.keymap"
  
jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    #uses: urob/zmk/.github/workflows/build-user-config.yml@build-with-submodules
