CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2

CONFIG_ZMK_SLEEP=n
CONFIG_ZMK_EXT_POWER=y
CONFIG_ZMK_DISPLAY=n

# Increase polling rate - default is 9ms = 111 hz polling rate, 2ms = 500hz, 1ms = 1000hz
CONFIG_USB_HID_POLL_INTERVAL_MS=1

# Enable fetching split peripheral battery levels to the central side
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

#Enable central reporting of split battery levels to hosts
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
