file_format: "1"
id: corne
name: Corne
type: shield
url: https://github.com/foostan/crkbd/
requires: [pro_micro]
exposes: [i2c_oled, nice_view_header]
features:
  - keys
  - display
  - underglow
siblings:
  - corne_left
  - corne_right
  - corne_central
  - corne_dongle
  - corne_dongle_reset
